### ISSUE TITLE
License problem?

### ISSUE THREAD

**Issue by heberleh** [tommilligan/color-blind-checker#27]
Very nice tool and blog post! Thanks for that!

I'm writing because I was overviewing available tools around color-blindness, and they all seem to have a License problem, that licenses are noncommercial.

Since your tool uses  "color-blind": "^0.1.1", I would like to point you to this discussion: https://github.com/skratchdot/color-blind/issues/3 where @notlee points out that the license may be wrong.

https://github.com/jkulesza/peacock has the same problem and they decided not to include a license, and just point in the Readme that the code is for noncomercial purposes.

However, we see Microsoft using color-blind too: https://github.com/skratchdot/color-blind/network/dependents?package_id=UGFja2FnZS0xMzQ2ODg4NA%3D%3D

Anything you know on this topic to help us to be sure?
Many thanks in advance.

**Comment by tommilligan** [comment]
I don't know I'm afraid - I've never had to use this for commercial use, so haven't investigated further.

As far as this repository goes, the licence is okay for commercial use, but I can't speak on behalf of `color-blind`.
